### ISSUE TITLE
Complete Loader class documentation

### ISSUE THREAD

**Issue by NicklessOne** [inkasadev/inks2d#4]
## Search Terms

documentation, Loader

## Problem

The documentation of the [Loader class](https://github.com/inkasadev/inks2d/blob/main/packages/lib/src/Loader.ts) is incomplete.

## Suggested Solution

Complete the Loader class documentation

**Comment by Alef-gabriel** [comment]
I can take this?

**Comment by NicklessOne** [comment]
Sure! I will assign it to you.
